# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/genesys2.xdc

# IP: ip/dvi_pll/dvi_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dvi_pll || ORIG_REF_NAME==dvi_pll}]
