# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/lab/projects/tonegen/tonegen.srcs/sources_1/ip/sine_rom/sine_rom.xci
# IP: The module: 'sine_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/lab/projects/tonegen/tonegen.srcs/sources_1/ip/sine_rom/sine_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dave/lab/projects/tonegen/tonegen.srcs/sources_1/ip/sine_rom/sine_rom.xci
# IP: The module: 'sine_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/lab/projects/tonegen/tonegen.srcs/sources_1/ip/sine_rom/sine_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
