# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/lab/projects/audio1/audio1.srcs/sources_1/ip/audio_delay_fifo/audio_delay_fifo.xci
# IP: The module: 'audio_delay_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/lab/projects/audio1/audio1.srcs/sources_1/ip/audio_delay_fifo/audio_delay_fifo/audio_delay_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_delay_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/lab/projects/audio1/audio1.srcs/sources_1/ip/audio_delay_fifo/audio_delay_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_delay_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dave/lab/projects/audio1/audio1.srcs/sources_1/ip/audio_delay_fifo/audio_delay_fifo.xci
# IP: The module: 'audio_delay_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/lab/projects/audio1/audio1.srcs/sources_1/ip/audio_delay_fifo/audio_delay_fifo/audio_delay_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_delay_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/lab/projects/audio1/audio1.srcs/sources_1/ip/audio_delay_fifo/audio_delay_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_delay_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
