# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/lab/projects/ex6/ex6.srcs/sources_1/ip/sys_mmcm/sys_mmcm.xci
# IP: The module: 'sys_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/lab/projects/ex6/ex6.srcs/sources_1/ip/sys_mmcm/sys_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/lab/projects/ex6/ex6.srcs/sources_1/ip/sys_mmcm/sys_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/lab/projects/ex6/ex6.srcs/sources_1/ip/sys_mmcm/sys_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/dave/lab/projects/ex6/ex6.srcs/sources_1/ip/sys_mmcm/sys_mmcm.xci
# IP: The module: 'sys_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/lab/projects/ex6/ex6.srcs/sources_1/ip/sys_mmcm/sys_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/lab/projects/ex6/ex6.srcs/sources_1/ip/sys_mmcm/sys_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/lab/projects/ex6/ex6.srcs/sources_1/ip/sys_mmcm/sys_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
