# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/lab/projects/voice_corruptor/voice_corruptor.srcs/sources_1/ip/delay_ram/delay_ram.xci
# IP: The module: 'delay_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/lab/projects/voice_corruptor/voice_corruptor.srcs/sources_1/ip/delay_ram/delay_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dave/lab/projects/voice_corruptor/voice_corruptor.srcs/sources_1/ip/delay_ram/delay_ram.xci
# IP: The module: 'delay_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/lab/projects/voice_corruptor/voice_corruptor.srcs/sources_1/ip/delay_ram/delay_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
